// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nightclub.Context;

#nullable disable

namespace Nigthclub.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20240227234301_FixCompleteDatabaseDesign")]
    partial class FixCompleteDatabaseDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nightclub.Models.Artist", b =>
                {
                    b.Property<int>("Id_artist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_artist"));

                    b.Property<int>("document_Id_type_document")
                        .HasColumnType("int");

                    b.Property<string>("document_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary_artist")
                        .HasColumnType("int");

                    b.Property<string>("surname_artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_artist");

                    b.HasIndex("document_Id_type_document");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Nightclub.Models.Assistant", b =>
                {
                    b.Property<int>("Id_assistant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_assistant"));

                    b.Property<int>("document_Id_type_document")
                        .HasColumnType("int");

                    b.Property<string>("document_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_assistant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname_assistant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_assistant");

                    b.HasIndex("document_Id_type_document");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("Nightclub.Models.Assistant_role", b =>
                {
                    b.Property<int>("Id_assistant_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_assistant_role"));

                    b.Property<string>("name_assistant_role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_assistant_role");

                    b.ToTable("Assistant_roles");
                });

            modelBuilder.Entity("Nightclub.Models.Client", b =>
                {
                    b.Property<int>("Id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_client"));

                    b.Property<int>("document_Id_type_document")
                        .HasColumnType("int");

                    b.Property<string>("document_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname_client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_client");

                    b.HasIndex("document_Id_type_document");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Nightclub.Models.Event", b =>
                {
                    b.Property<int>("Id_event")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_event"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("date");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_event");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Nightclub.Models.Event_artist", b =>
                {
                    b.Property<int>("Id_event_artist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_event_artist"));

                    b.Property<int>("assistant_Id_assistant")
                        .HasColumnType("int");

                    b.HasKey("Id_event_artist");

                    b.HasIndex("assistant_Id_assistant");

                    b.ToTable("Event_Artists");
                });

            modelBuilder.Entity("Nightclub.Models.Event_assistant", b =>
                {
                    b.Property<int>("Id_event_assistant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_event_assistant"));

                    b.Property<int>("assistant_Id_assistant")
                        .HasColumnType("int");

                    b.Property<int>("rol_Id_type_rol")
                        .HasColumnType("int");

                    b.HasKey("Id_event_assistant");

                    b.HasIndex("assistant_Id_assistant");

                    b.HasIndex("rol_Id_type_rol");

                    b.ToTable("Event_Assistants");
                });

            modelBuilder.Entity("Nightclub.Models.Ticket", b =>
                {
                    b.Property<int>("Id_ticket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ticket"));

                    b.Property<int>("client_Id_client")
                        .HasColumnType("int");

                    b.Property<DateOnly>("date_join")
                        .HasColumnType("date");

                    b.Property<int>("event_Id_event")
                        .HasColumnType("int");

                    b.Property<string>("qr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_ticket");

                    b.HasIndex("client_Id_client");

                    b.HasIndex("event_Id_event");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Nightclub.Models.Type_document", b =>
                {
                    b.Property<int>("Id_type_document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_type_document"));

                    b.Property<string>("name_type_document")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_type_document");

                    b.ToTable("Type_documents");
                });

            modelBuilder.Entity("Nightclub.Models.Type_rol", b =>
                {
                    b.Property<int>("Id_type_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_type_rol"));

                    b.Property<string>("name_rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_type_rol");

                    b.ToTable("Type_Rols");
                });

            modelBuilder.Entity("Nightclub.Models.Artist", b =>
                {
                    b.HasOne("Nightclub.Models.Type_document", "document_")
                        .WithMany()
                        .HasForeignKey("document_Id_type_document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("document_");
                });

            modelBuilder.Entity("Nightclub.Models.Assistant", b =>
                {
                    b.HasOne("Nightclub.Models.Type_document", "document_")
                        .WithMany()
                        .HasForeignKey("document_Id_type_document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("document_");
                });

            modelBuilder.Entity("Nightclub.Models.Client", b =>
                {
                    b.HasOne("Nightclub.Models.Type_document", "document_")
                        .WithMany("client")
                        .HasForeignKey("document_Id_type_document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("document_");
                });

            modelBuilder.Entity("Nightclub.Models.Event_artist", b =>
                {
                    b.HasOne("Nightclub.Models.Assistant", "assistant_")
                        .WithMany()
                        .HasForeignKey("assistant_Id_assistant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assistant_");
                });

            modelBuilder.Entity("Nightclub.Models.Event_assistant", b =>
                {
                    b.HasOne("Nightclub.Models.Assistant", "assistant_")
                        .WithMany()
                        .HasForeignKey("assistant_Id_assistant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nightclub.Models.Type_rol", "rol_")
                        .WithMany("event_Assistants")
                        .HasForeignKey("rol_Id_type_rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assistant_");

                    b.Navigation("rol_");
                });

            modelBuilder.Entity("Nightclub.Models.Ticket", b =>
                {
                    b.HasOne("Nightclub.Models.Client", "client_")
                        .WithMany("ticket")
                        .HasForeignKey("client_Id_client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nightclub.Models.Event", "event_")
                        .WithMany("ticket")
                        .HasForeignKey("event_Id_event")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client_");

                    b.Navigation("event_");
                });

            modelBuilder.Entity("Nightclub.Models.Client", b =>
                {
                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Nightclub.Models.Event", b =>
                {
                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Nightclub.Models.Type_document", b =>
                {
                    b.Navigation("client");
                });

            modelBuilder.Entity("Nightclub.Models.Type_rol", b =>
                {
                    b.Navigation("event_Assistants");
                });
#pragma warning restore 612, 618
        }
    }
}
