// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nightclub.Context;

#nullable disable

namespace Nigthclub.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nightclub.Models.Assistant_role", b =>
                {
                    b.Property<int>("Id_assistant_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_assistant_role"));

                    b.Property<string>("name_assistant_role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_assistant_role");

                    b.ToTable("Assistant_roles");
                });

            modelBuilder.Entity("Nightclub.Models.Client", b =>
                {
                    b.Property<int>("Id_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_client"));

                    b.Property<int>("document_Id_type_document")
                        .HasColumnType("int");

                    b.Property<string>("document_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name_client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surname_client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_client");

                    b.HasIndex("document_Id_type_document");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Nightclub.Models.Type_document", b =>
                {
                    b.Property<int>("Id_type_document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_type_document"));

                    b.Property<string>("name_type_document")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_type_document");

                    b.ToTable("Type_documents");
                });

            modelBuilder.Entity("Nightclub.Models.Client", b =>
                {
                    b.HasOne("Nightclub.Models.Type_document", "document_")
                        .WithMany("client")
                        .HasForeignKey("document_Id_type_document")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("document_");
                });

            modelBuilder.Entity("Nightclub.Models.Type_document", b =>
                {
                    b.Navigation("client");
                });
#pragma warning restore 612, 618
        }
    }
}
